# Generated by Django 6.0 on 2026-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('esewa', 'esewa'), ('khalti', 'Khalti')], default='cash_on_delivery', max_length=20),
        ),
    ]
