# Generated by Django 6.0 on 2026-02-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('esewa', 'esewa'), ('khalti', 'Khalti')], default='cash_on_delivery', max_length=20),
        ),
    ]
